[project]
name = "mtg-gen-gradio"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = [
    "gradio",
    "numpy",
    "openai",
    "pandas",
	"pillow",
    "python-dotenv",
    "pydantic",
]
